development:
  adapter: postgresql
  encoding: unicode
  database: ticketee_development
  pool: 5
  username: Zachary
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ticketee_test
  pool: 5
  username: Zachary
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ticketee_production
  pool: 5
  username: Zachary
  password: 