source 'https://rubygems.org'

ruby '1.9.3'
gem 'rails', '~> 3.2'
gem 'dynamic_form', '1.1.4'
gem 'devise', '2.1.0'
gem 'cancan', '1.6.7'
gem 'thin'
# gem 'spork'
# gem 'spork-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'zurb-foundation', '~> 2.2'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'debugger'


group :test, :development do
  gem 'gmail', '~> 0.4'
	gem 'rspec-rails', '~> 2.11'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'sqlite3'
end

group :test do
	gem 'capybara', '1.1.2'
	gem 'factory_girl', '2.6.4'
  gem 'email_spec', '1.2.1'
  # gem 'database_cleanrer'
  gem 'launchy'
	gem 'simplecov', :require => false
end

group :production do
  gem 'pg'
  gem 'therubyracer'
end